### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by leejanghe** [leejanghe/Challenge-Mini-Project#1]
## dark mode

한번쯤은 경험해본 다크모드!! 많은 서비스가 다크모드를 지원하고 있고 실제로 사용자 입장에서도 선호도가 높다. 그래서 이번 미니 프로젝트는 다크모드를 중점으로 둔 미니프로젝트를 진행 하였다.

### 방법

우선 다크모드하기 위해선 CSS 설정이 중요하다. 전역변수를 활용하여 밝을때의 글자색과 배경색, 어두울때 글자색과 배경색을 지정해준다.

```css
:root {
  --primary-color: #000;
  --secondary-color: #fff;
}

html.dark {
  --primary-color: #fff;
  --secondary-color: #000;
}

html.dark {
  background-color: #111;
  color: var(--primary-color);
}
```

css설정을 마무리 하면 js를 활용해서 html에 dark 클래스네임을 조절하면 된다. 여기서 중요 포인트는 contains함수를 활용하여 html에 클래스가 dark가 포함하는지 아닌지 조건문을 활용해서 사용하면 된다.

```js
toggle.addEventListener('click', (e) => {
    const html = document.querySelector('html')
    if (html.classList.contains('dark')) {
        html.classList.remove('dark')
        e.target.innerHTML = 'Dark mode'
    } else {
        html.classList.add('dark')
        e.target.innerHTML = 'Light mode'
    }
})
```

여기서 클래스명이 꼭 dark일 필요는 없다. 클래스명은 작명해서 사용하면 된다. 그리고 취향에 따라 토글함수를 사용해도 되며 localStorage에 저장해서 사용자의 편의성을 높이는 방법도 있다.

옛날엔 다크모드 구현이 어려울 줄 알고 무서웠는데... 실제로 도전해보니 나름 할만하다는 생각이 든다!

[참고사이트](https://velog.io/@yijaee/%EB%8B%A4%ED%81%AC%EB%AA%A8%EB%93%9C-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0)
